= Validation and Verification : Course Notes
Oscar Luis Vera-Pérez <oscarlvp@gmail.com>
:sectnums:
:stem:
:imagesdir: images/
:source-highlighter: pygments
:pygments-style: monokai
:icons: font
:toc: left
:toclevels: 4
:xrefstyle: short

:numbered!:
== Note about the notes

These course notes have been initially inspired from the (inherited and redefined) conferences taught by Jean-Marc Jézéquel, Yves Le Traon, Benoit Baudry and Benoit Combemale, who also provided feedback and proofread the material.

The initial content has been enriched with materials from the https://cs.gmu.edu/~offutt/softwaretest/["Introduction to Software Testing"] book written by Paul Ammann and Jeff Offutt, https://www.fuzzingbook.org/["The Fuzzing Book"] by Andreas Zeller, Rahul Gopinath, Marcel Böhme, Gordon Fraser, and Christian Holler and the https://www.youtube.com/playlist?list=PL3bOx_OjZk8EvOo3un0xeGpXlqGT2YQXa[online material on GUI testing] published by Tanja Vos.
Many other bibliographical sources and materials were also used and appear in the <<99-references.adoc#_references,References>> section.

As part of the course, students had to complete a set of exercises for each topic. These exercises can be consulted in the following links:

- https://github.com/validation-and-verification-istic/2020-tp1-introduction[Introduction]
- https://github.com/validation-and-verification-istic/2020-tp2-static-analysis[Code quality and static analysis]
- https://github.com/validation-and-verification-istic/2020-tp3-testing[Testing]
- https://github.com/validation-and-verification-istic/2020-tp4-fuzzing[Fuzzing]
- https://github.com/validation-and-verification-istic/2020-tp5-gui[GUI testing]

In addition, students had to complete a project in which they were given the source code of a faulty file compression application. The students had to put in practice what they learned to find and correct the faults and to improve the quality of the application code. Details of the project can be found https://github.com/validation-and-verification-istic/2020-project-squeezer[here].

WARNING: These notes are and will always be a work in progress. Any feedback is welcome. They are distributed under the Creative Commons Zero v1.0 Universal license.

////
TODO:
Topics to include in the future:
    - Variability
    - Metamorphic testing
    - AI 4 Testing and Testing 4 AI
        - Intelligent autocomplete and refactoring
        - Learning mutation operators
        - https://www.sciencedirect.com/science/article/abs/pii/S0925231219316698
        - https://ieeexplore.ieee.org/abstract/document/8730151/references#references
        - Jonas Gillbergs
        - Mutation testing for neural networks
    - Design by contract
    - Search-based test generation
////

:numbered:
include::01-introduction.adoc[]

include::02-static-analysis.adoc[]

include::03-testing.adoc[]

include::04-fuzzing.adoc[]

include::05-gui-testing.adoc[]

:numbered!:
include::99-references.adoc[]