name: Build site
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 2.6 
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Cloning public branch
      run: git clone --branch public https://oscarlvp:${{ secrets.GITHUB_TOKEN }}@github.com/oscarlvp/vandv-classes.git output
    - name: Building site
      run: |
        make install
        make html
    - name: Updating remote branch
      run: |
        cd output
        git add .
        git commit -m "Building site from action"
        git push https://oscarlvp:${{ secrets.DEPLOY_TOKEN }}@github.com/oscarlvp/vandv-classes.git
        
